### ISSUE TITLE
No settings were set in VSCode subdirectories

### ISSUE THREAD

**Issue by tinovyatkin** [yarax/eslint-plugin-typelint#8]
Fails with error "No settings were set" in Visual Studio Code subdirectories even if settings are set at project root `.eslintrc`

**Comment by yarax** [comment]
Hard to say, just installed plugin from scratch it seems to work. 
Could you please provide you eslint config?
Or you can compare it with example project https://github.com/yarax/typelint-example

**Comment by tinovyatkin** [comment]
May be I explained the issue wrong: plugin shows no error if `.eslintrc` presented in the directory with `.js` files. However, in any subdiretory with `.js`, but without local `.eslintrc` it does throw this error, instead of using root `.eslintrc` file. Seems like inheritance problem for me...

**Comment by yarax** [comment]
Yes, probably your root .eslintrc is located not on the node_modules level?

**Comment by tinovyatkin** [comment]
it's located on the node_modules level, and typelint is loaded from it

**Comment by yarax** [comment]
I put example config (without typelint settings) to sub directory "test" in https://github.com/yarax/typelint-example
So if you run `./node_modules/.bin/eslint test/` you will see, that typelint will find an error and works properly.
