### ISSUE TITLE
eslint unable to find local eslint-plugin-typelint

### ISSUE THREAD

**Issue by SebastienDaniel** [yarax/eslint-plugin-typelint#9]
My `eslint` is installed locally and so is `eslint-plugin-typelint`.
My entire eslint configuration works flawlessly, except when I add the "typelint" plugin.

The message I'm getting is:
![image](https://cloud.githubusercontent.com/assets/445482/20871373/16d78af4-ba63-11e6-9ca7-fcfa98e01498.png)

eslint version: `3.11.1`
npm version: `3.10.3`
node version: `6.6.0`

**Comment by yarax** [comment]
Could you show your .eslintrc? Or you can compare it with example project https://github.com/yarax/typelint-example/blob/master/.eslintrc.yml

**Comment by SebastienDaniel** [comment]
Thanks for the quick reply!

I looked into this a little more and I believe the issue is that I am not providing any typelint settings, specifically models.

I may have been confused by the description of the plugin: *I thought it did basic typechecking using existing JSDoc notation for functions and function calls, etc.*

In any case, here is the `eslintrc` config:

```json
{
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true
    }
  },
  "env": {
    "browser": true,
    "node": true,
    "commonjs": true,
    "es6": true,
    "mocha": true
  },
  "extends": "eslint:recommended",
  "plugins": ["import", "typelint"],
  "rules": {
    "no-extra-parens": 1,
    "valid-jsdoc": 1,
    "default-case": 2,
    "curly": 1,
    "eqeqeq": ["error", "always", {"null": "ignore"}],
    "no-caller": 2,
    "no-eval": 2,
    "no-extend-native": 1,
    "no-floating-decimal": 1,
    "no-invalid-this": 1,
    "no-magic-numbers": 1,
    "no-new-func": 1,
    "no-new-wrappers": 1,
    "no-sequences": 1,
    "no-throw-literal": 1,
    "no-with": 2,
    "vars-on-top": 1,
    "no-useless-call": 1,
    "no-useless-concat": 1,
    "wrap-iife": 2,
    "yoda": 2,
    "comma-dangle": [1, "never"],
    "indent": [1, "tab"],
    "new-cap": 2,
    "new-parens": 2,
    "one-var": [1, "never"],
    "quotes": [1, "double"],
    "arrow-parens": 1,
    "arrow-spacing": 1,
    "arrow-body-style": 1,
    "prefer-const": 1
  },
  "globals": {
    "expect": true,
    "sinon": true,
    "sandbox": true
  }
}
```

**Comment by yarax** [comment]
As about typelint itself, it does typechecking for primitive types and for complex types basing on pointed models, but only inside of the function. Because for checking function calls you need to parse whole the project and eslint doesn't do it.
But your error is literally about that eslint couldn't find the plugin. 
I've just tried your eslint config, being installed `npm i --save-dev eslint eslint-plugin-typelint eslint-plugin-import` to the empty project and it worked for me.

**Comment by SebastienDaniel** [comment]
Thanks for the info about eslint. I should have known that ;)
The only other info that could be of use is that I'm on Linux.
